### ISSUE TITLE
Crear pagina de Productos

### ISSUE THREAD

**Issue by mariavillalba06** [mariavillalba06/repo-tp2#2]
Crear un archivo con el nombre productos.html en carpeta templates.

Dentro de Productos construir la siguiente estructura html, con las siguientes consideraciones:
-Debe incluir una etiqueta <header>: incluye un título nivel h1 y una imagen de presentación, <img> debe
incluir los atributos src, alt y title para la imagen.
-Para almacenar las imágenes crear una nueva carpeta dentro de la carpeta static con el nombre images.
<nav>: incluye una lista sin ordenar <ul> donde cada ítem es un enlace <a> que redirige a las siguientes
páginas a construir:
 Inicio (index.html)
 Productos (productos.html)
 Consejos de salud (consejos.html)
 Servicio de paseos (servicios.html)
 Sucursales (sucursales.html)
 Contáctanos (contacto.html)

Muestra una lista con imágenes y descripción de productos
-<aside>: Incluir contenido adicional que mantenga relación con el sitio.
-<footer>: incluye un párrafo <p> mostrando texto que incluya, por ejemplo: Copyright 2023 - MascoTienda - Diseñado por Grupo 37 – Jujuy – República Argentina

**Comment by KevinChosco** [comment]
Listo
