### ISSUE TITLE
TP4_Creación del modelo, controlador y uso de Thymeleaf en la página sucursales

### ISSUE THREAD

**Issue by SebasMullicundo** [mariavillalba06/repo-tp2#24]
Dentro del paquete “model” debe crear una entidad que represente a las sucursales de la tienda. Esta entidad debe incluir las propiedades necesarias para almacenar la información de los productos, así como los getter, setter y constructores.
En el paquete “listas” crear un objeto que permita almacenar un listado de las sucursales en la cual debe haber un almacenamiento previo.
En el paquete “controller” se debe crear el controlador necesario y sus funciones correspondiente para mostrar la página “sucursales.html” en pantalla. Este controlador debe ser responsable de manejar las acciones relacionadas con la creación, el guardado y la eliminación de una sucursal.
Se debe diseñar un formulario que permita ingresar los datos correspondientes a las sucursales, siendo capaz de interactuar con el controlador y la lista de productos.
Por último, actualizar la página “sucursales.html” con las funciones proporcionadas por Thymeleaf para garantizar el funcionamiento.

**Comment by KevinChosco** [comment]
Terminado
