### ISSUE TITLE
TP6_Creación de la interfaz y la clase de implementación para el servicio de productos

### ISSUE THREAD

**Issue by SebasMullicundo** [mariavillalba06/repo-tp2#75]
**Tareas:**
1. En el paquete "service", crea la interfaz "IProductoService" para declarar los métodos correspondientes a los productos. Los métodos abstractos de esta interfaz deben permitir realizar las siguientes acciones:
   -    Listar productos
   -    Guardar un nuevo producto
   -    Modificar un producto existente
   -    Eliminar un producto
   -    Buscar productos según un criterio específico
   -    Recuperar un objeto del modelo de datos

2.  En el paquete "service.imp", se debe crear la clase "ProductoServiceImp" que implemente la interfaz "IProductoService". Esta debe de implementar todos los métodos declarados en la interfaz y de proporcionar la lógica necesaria para cada acción mencionada anteriormente.

3.  En la clase del paquete "controller" y "service.imp" correspondiente a productos, se deben aplicar la inyección de dependencia utilizando la anotación @Autowired que permitirá la correcta instancia y gestión de las dependencias necesarias para cada clase.

4.  Dentro de “IListaService” declare los métodos que permita obtener la lista de las categorías de productos y que sean implementadas por “ListaServiceImp”. Esta lista debe ser usada de manera dinámica dentro de “nuevo_producto”.

**Comment by KevinChosco** [comment]
Implementación terminada!
