### ISSUE TITLE
TP6_Creación de la interfaz y la clase de implementación para el servicio de sucursal

### ISSUE THREAD

**Issue by SebasMullicundo** [mariavillalba06/repo-tp2#76]
1. En el paquete "service", crea la interfaz "ISucursalService" para declarar los métodos correspondientes a las sucursales. Los métodos abstractos de esta interfaz deben permitir realizar las siguientes acciones:
   -  Listar las sucursales
   -  Guardar una nueva sucursal
   -  Modificar una sucursal existente
   -  Eliminar una sucursal
   -  Buscar una sucursal según un criterio específico
   -  Recuperar una sucursal del modelo de datos

2. En el paquete "service.imp", se debe crear la clase "SucursalServiceImp" que implemente la interfaz "ISucursalService". Esta debe de implementar todos los métodos declarados en la interfaz y de proporcionar la lógica necesaria para cada acción mencionada anteriormente.

3. En la clase del paquete "controller" y "service.imp" correspondiente a sucursal, se deben aplicar la inyección de dependencia utilizando la anotación @Autowired que permitirá la correcta instancia y gestión de las dependencias necesarias para cada clase.

4. Dentro de “IListaService” declare los métodos que permita obtener la lista de las provincias y que sean implementadas por “ListaServiceImp”. Esta lista debe ser usada de manera dinámica dentor de “nueva_sucursal”.

**Comment by KevinChosco** [comment]
Implementacion realizada!
